spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
server:
  error:
    include-message: always
    include-binding-errors: always